In [ ]:
#https://www.youtube.com/watch?v=gnKbAAVUzro&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK

**Learn more on how to slice through multidimensional arrays and how to search through arrays more detailed. **


In [ ]:
import numpy as np

In [ ]:
# create a numpy array and print it's shape
np1=np.array([0,1,2,3,4,5,6,7,8,9])
np1.shape

(10,)

In [ ]:
#arange means from 0 to the number excluding last number
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# you can specify the step
np3=np.arange(3,10,2)
np3


array([3, 5, 7, 9])

In [ ]:
#create an array for zeroes
np4=np.zeros(8)


In [ ]:
# multidimentional array
np5=np.zeros((3,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(np.full((10,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
np7=np.full((10,2),6)
np7

array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

In [ ]:
# convert python list to numpy
list=[1,2,3,4,5,6,7,8,9]
np8=np.array(list)

In [ ]:
import numpy as np
np_test=np.array([[1,4,5],[6,7,8],[5,6,7],[9,8,7]])
print(np_test)
print(np_test.shape)

[[1 4 5]
 [6 7 8]
 [5 6 7]
 [9 8 7]]
(4, 3)


In [ ]:
print(np_test[:,0:2])
print(np_test[::-1])

[[1 4]
 [6 7]
 [5 6]
 [9 8]]
[[9 8 7]
 [5 6 7]
 [6 7 8]
 [1 4 5]]


In [ ]:
# slicing arrays
print(np1)
# we want to return 2,3,4,5,
print(np1[2:6])
print(np1[-4:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[6 7 8 9]


In [ ]:
print(np1[-5:])
print(np1[-5:-1])


[5 6 7 8 9]
[5 6 7 8]


In [ ]:
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# slicing with step
print(np1[0:5:2])
print(np1[::2])


[0 2 4]
[0 2 4 6 8]


In [ ]:
np_try=np.array([1,2,3,4,5,6,7,8,9,10,1,11,12,13,14,15])
np.sort(np_try)
print(np_try[::-1])
print(np_try[4:-2:2])

[15 14 13 12 11  1 10  9  8  7  6  5  4  3  2  1]
[ 5  7  9  1 12]


In [ ]:
# 2d array
np11=np.array([[1,2,7,8],[3,4,5,6]])
print(np11)

[[1 2 7 8]
 [3 4 5 6]]


In [ ]:
np_test=np.array([[1,2,3],[3,4,5],[4,5,6]])


In [ ]:
#pull out a single element
print(np11[0,1])
#pull out a slice
print(np11[0,2:])

2
[7 8]


In [ ]:
# some universal function of numpy
#squarer root
np_root=np.sqrt(np1)
#absolute value
print(np.abs([-4,-5,7,8]))
# exponent
print(np.exp(np1))
# min or max
print(np.min(np1))
print(np.max(np1))
print(np.log(np1))

[4 5 7 8]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
0
9
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


<ipython-input-18-d48f226d2dd3>:11: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))


In [ ]:
# copy vs view for numpy
# view also copies but it changes elements if we change the original array. If you make a change in view/original then the view/original
# will change
np12=np.array([0,1,2,3,4,5,6,7,8,9])
np13=np12.view()
np14=np12.copy()
np12[5]=90

In [ ]:
print("original np12", np12)
print("view", np13)
print("copy", np14)


original np12 [ 0  1  2  3  4 90  6  7  8  9]
view [ 0  1  2  3  4 90  6  7  8  9]
copy [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# shape and reshape numpy arrays
np15=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np15)
print(np15.shape)
np16=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np16)
print(np16.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [ ]:
np17=np15.reshape(6,2)
#print(np17)
np18=np15.reshape(12,).reshape(2,3,2)
print(np18)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#iterating through numpy arrays

In [ ]:
np_it=np.array([1,2,3,4,5,6,7,8,9])
a=[i for i in np_it if i>5]
print(a)

[6, 7, 8, 9]


In [ ]:
print(np_it[::-1])
len(np_it)

[9 8 7 6 5 4 3 2 1]


9

In [ ]:
np_it_ndim=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np_it_ndim:
  print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [ ]:
for x in np_it_ndim:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10


In [ ]:
#3d array
np_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np_3d:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#sorting arrays
np_s=[6,5,4,7,8,9]
print(np.sort(np_s))
# sort returns a copy but doesn't change the original.

[4 5 6 7 8 9]


In [ ]:
# searching through numpy arrays
np_search=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(np_search==6)
print(x)

(array([5]),)


In [ ]:
np_search=np.array([1,2,3,4,5,6,7,8,9,10]) # didn't understand.
index=np.where(np_search>5)
index

(array([5, 6, 7, 8, 9]),)

In [ ]:
np_search_new=[]
for a in index:
  np_search_new.append(a)
print(np_search_new)


[array([5, 6, 7, 8, 9])]


In [ ]:
np_search1= np.array([1,2,3,4,5,6,7,8,9,20])
x1=np.where(np_search1>6)
x1

(array([6, 7, 8, 9]),)

In [ ]:
np_search=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(np_search>4)
print(x)

(array([4, 5, 6, 7, 8, 9]),)


In [ ]:
np_one=np.array([1,2,3,4,5,6,7,8,9])
np_2=np.where(np_one>5)


In [ ]:
#return even items
np.where(np_search%2==0)


(array([1, 3, 5, 7, 9]),)

In [ ]:
#filtering numpy arrays
np_filter=np.array([1,2,4,5,6,7,7,7])
x=[True, False,True, False,True, False,True,True]
print(np_filter)
print(np_filter[x])

[1 2 4 5 6 7 7 7]
[1 4 6 7 7]


In [ ]:
np_test=np.array([[5,6,8,9],[7,2,3,9],[4,5,6,7]])
np_test

array([[5, 6, 8, 9],
       [7, 2, 3, 9],
       [4, 5, 6, 7]])

In [ ]:
np_test[0:,1:2] # didn't understand

array([[6],
       [2],
       [5]])

In [ ]:
np.where(np_test[0:,1:2]==5)

(array([2]), array([0]))

In [ ]:
list1 = [1,2,4]
list2 = [1,3,4]
#Output: [1,1,2,3,4,4]

In [ ]:
array1=np.array(list1)
array2=np.array(list2)

In [ ]:
def testil(n):
  testi=np.arange(0,10**n,1)
  return testi

In [ ]:
testil(6)

array([     0,      1,      2, ..., 999997, 999998, 999999])