In [ ]:
# https://www.udemy.com/course/data-structures-and-algorithms-bootcamp-in-python/learn/lecture/18848308#notes

**1D array**

In [ ]:
# How to create an array in python:
# 1d arrays
import numpy as np
# create an empty array
empty_array=np.array([])
print(empty_array)
# create non empty array
non_empty_array=np.array([1,2,3,4,5], dtype=int)
print(non_empty_array)
# inserting into array
non_empty_array1=np.insert(non_empty_array, 0, 7)
print(non_empty_array1)
# traversal operation
for i in range(len(non_empty_array1)):
  print(i, end=" \n")
# travers using a function
def traverse_arra(arr):
  for i in arr:
    print(i, end=" ")
traverse_arra(non_empty_array)

[]
[1 2 3 4 5]
[7 1 2 3 4 5]
0 
1 
2 
3 
4 
5 
1 2 3 4 5 

In [ ]:
23


In [ ]:
array1=np.array([5,7,8,5,0])
print(array1[3])
#function to access element by index
def access_by_index(array,index):
  if len(array)<index+1:
    print('index out of bound')
  else:
    print(f'the index {index} holds element {array[index]}')
access_by_index(array1,2)

5
the index 2 holds element 8


In [ ]:
# access to elemtnt by index


index is out of bounds


In [ ]:
# slicing an array
def index_with_slice(array, index_begins, index_ends):
  if index_ends+1>len(array):
    print("index out of bounds")
  elif index_begins==index_ends:
    return array[index_begins]
  elif index_begins>index_ends:
    print("wrong index")
  else:
    return array[index_begins:index_ends]
print(index_with_slice(array1, 3, 4))
print(array1)

[5]
[5 7 8 5 0]


In [ ]:
# searching for element in array
search_array=np.array([1,2,6,78,99,45])
def searching_array(array, target):
  for i in range(len(array)):
    if array[i]==target:
      print("the target", target, "is in", i)
searching_array(search_array,6)
print(np.where(search_array==78))


the target 6 is in 2
(array([3]),)


In [ ]:
# deleting an element in array
delete_array=np.array([1,2,4,5,6,7,9,14])
delete_array1=np.delete(delete_array,4)
print(delete_array1)

[ 1  2  4  5  7  9 14]


In [ ]:
# write a function to delete array by index
def delete_element_by_index(array, index):
  if index+1>len(array):
    print("out of bounds")
  else:
    print(f'the element {array[index]} from {array} is deleted \n , and new array is {np.delete(array,index)}')

delete_element_by_index(np.array([1,2,3,4,5,6,7]), 3)

the element 4 from [1 2 3 4 5 6 7] is deleted 
 , and new array is [1 2 3 5 6 7]


In [ ]:
# exercise for 1D array. Do it later. lecture 34

In [ ]:
# delete array element by value not index
delete_value=np.array([88,99,54,23,26,27])
def delete_by_value(arr, value):
  for i in range(len(arr)):
    if arr[i]==value:
      print(f'the value {value} is deleted from {arr}, \n new array is {np.delete(arr,i)}')
delete_by_value(delete_value,27)

the value 27 is deleted from [88 99 54 23 26 27], 
 new array is [88 99 54 23 26]


**2D array**

In [ ]:
# creating two dimensional array
import numpy as np
twoDArray=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[2,7,9,12]])
print(twoDArray)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 2  7  9 12]]


In [ ]:
# insertion a new value into twoD array
twoDArraynew=np.insert(twoDArray, 0, [11,22,33,44], axis=0) #row wise
twoDArraynew1=np.insert(twoDArray, 0, [11,22,33,44], axis=1) #column wise

In [ ]:
print(twoDArraynew)
twoDArraynew.shape[0]

[[11 22 33 44]
 [ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 2  7  9 12]]


5

In [ ]:
# access into twodimensional array
def access_two_d_array(array, index_row, index_column):
  if index_row+1>array.shape[0] or index_column+1>array.shape[1]:
    print("out of bounds")
  else:
    print(array[index_row,index_column])

access_two_d_array(twoDArray,2,1)
print(twoDArray)

6
[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 2  7  9 12]]


In [ ]:
# traversing to twod d array
def traverse_2d(array):
  for i in range(array.shape[0]):
    for j in range(array.shape[1]):
      print(array[i,j], end=" ")
traverse_2d(twoDArraynew)

11 22 33 44 1 2 3 4 3 4 5 6 5 6 7 8 2 7 9 12 

In [ ]:
twoDArray

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 2,  7,  9, 12]])

In [ ]:
# searching two d array
def searching_2d(array, target):
  for i in range(array.shape[0]):
    for j in range(array.shape[1]):
      if array[i][j]==target:
        return i,j
searching_2d(twoDArray,9)

(3, 2)

In [ ]:
# deletion of two d array
delete_array=np.array([[1,2,3,4],[2,7,8,9],[7,8,6,55],[7,12,34,56]])
np.delete(delete_array,0, axis=1)

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [ 8,  6, 55],
       [12, 34, 56]])

 <b>Section 4 list </b>


In [ ]:
#creating empty list
list1=[]
#non empty
list2=[1,2,3,'t',True]
print(list2)

[1, 2, 3, 't', True]


In [ ]:
# traversing a list
for i in list2:
  print(i)
print(3 in list2)
print(list2[::-1])

1
2
3
t
True
True
[True, 't', 3, 2, 1]


In [ ]:

# slice/delete
mylist=[1,2,3,4,5]
del(mylist[0])
print(mylist)
del(mylist[0:2])
print(mylist)

[2, 3, 4, 5]
[4, 5]


In [ ]:
def maxProfit(prices):
  buy=min(prices)
  for i in range(len(prices)):
    if prices[i]==min(prices):
      x=i
  new_prices=prices[x:]
  sell=max(new_prices)
  print(sell-buy)
maxProfit([7,6,4,3,1])

0




```
# This is formatted as code
```



In [ ]:
mylist=[1,2,3,4,4,5]
mylist.remove(4)
print(mylist)

[1, 2, 3, 4, 5]


In [ ]:
# searching for an element in the list
mylist=[10,20,30,40,50,60,70,80]
if 200 in mylist:
  print(200, "in the list")
else:
   print("not in the list")


not in the list


In [ ]:
#linear search
target=60
for i in range(len(mylist)):
  if mylist[i] ==target:
    print(i)

5


In [ ]:
# function for linear search
def linear_search(list, value):
  for i in range(len(list)):
    if list[i]==value:
      print(i)
linear_search(mylist,60)

5


In [ ]:
def another_linear_search(p_list, p_target):
  for i, value in enumerate(p_list):
    if value==p_target:
      return i
  return -1 # writing return-1 outside of the function means that the element doesn't exist in the list

another_linear_search([10,20,30,50,60], 60)

4

In [ ]:
print(mylist*3)
print(mylist+[23,34])

[10, 20, 30, 40, 50, 60, 70, 80, 10, 20, 30, 40, 50, 60, 70, 80, 10, 20, 30, 40, 50, 60, 70, 80]
[10, 20, 30, 40, 50, 60, 70, 80, 23, 34]


In [ ]:
# list functions: len, max, min, sum
a=[4,5,6,8,9,11,2,34,67]
print(max(a))
print(min(a))
print(len(a))


67
2
9


In [ ]:
sum=0
for i in range(len(a)):
  sum=sum+a[i]
print(sum)

146


In [ ]:
sum1=0
for i in mylist:
  sum1=sum1+i
print(sum1)
#print(sum(mylist))


360


In [ ]:
# do it later https://www.udemy.com/course/data-structures-and-algorithms-bootcamp-in-python/learn/lecture/18935902#notes
# splitting the list
a="Nesar Ahmed Titu"
aa="Nesar-Ahmed-Titu"
c=a.split(" ")
print(c)
d=aa.split("-")
print(d)
x=[i for i in a]
print(x)
print(a.split())

['Nesar', 'Ahmed', 'Titu']
['Nesar', 'Ahmed', 'Titu']
['N', 'e', 's', 'a', 'r', ' ', 'A', 'h', 'm', 'e', 'd', ' ', 'T', 'i', 't', 'u']
['Nesar', 'Ahmed', 'Titu']


In [ ]:
#
#delimiter.join(list)
#print("".join(b))
str1="My name is Nesar, I am not happy, but I will be happy soon."
str2=[a for a in str1]
print(str2)
str3="".join(str2)
print(str3)


['M', 'y', ' ', 'n', 'a', 'm', 'e', ' ', 'i', 's', ' ', 'N', 'e', 's', 'a', 'r', ',', ' ', 'I', ' ', 'a', 'm', ' ', 'n', 'o', 't', ' ', 'h', 'a', 'p', 'p', 'y', ',', ' ', 'b', 'u', 't', ' ', 'I', ' ', 'w', 'i', 'l', 'l', ' ', 'b', 'e', ' ', 'h', 'a', 'p', 'p', 'y', ' ', 's', 'o', 'o', 'n', '.']
My name is Nesar, I am not happy, but I will be happy soon.


In [ ]:
# list comprehension
fruit_list1 = ['Apple', 'Berry', 'Cherry', 'Papaya']
fruit_list2 = fruit_list1
fruit_list3 = fruit_list1[:]

fruit_list2[0] = 'Guava'
fruit_list3[1] = 'Kiwi'
print(fruit_list2)
print(fruit_list3)

['Guava', 'Berry', 'Cherry', 'Papaya']
['Apple', 'Kiwi', 'Cherry', 'Papaya']


In [ ]:
# recursion and save value to the list from list
empty_list=[]
lll=[6,7,8,9,10]
def list_recursion(lis):
  for i in range(len(lis)):
    empty_list.append(lis[i])
  return empty_list
list_recursion(lll)

[6, 7, 8, 9, 10]

**Section 5: Project array/list**

In [ ]:
from array import *
import numpy as np
days=int(input("How many days temereture you want? "))
total_temp=0
temps=[]
for i in range(1,days+1):
  temp=int(input("day:" + str(i)+ " highest temperature"))
  total_temp=total_temp+temp
  temp_list=temps.append(temp)
print(temp_list)




How many days temereture you want? 3
day:1 highest temperature23
day:2 highest temperature33
day:3 highest temperature33
None


In [ ]:
average=total_temp/i
count=0
for i in range(1,days+1):
  if temp>average:
    count=count+1
print(count)

3


In [ ]:
a=[25,56]
for i in range(len(a)):
  a.append(a[i])
print(a)

[25, 56, 25, 56]


**Section 8: Dictionary**

In [ ]:
# creating an empty dictionary in python
dictionary_empty={}
print(type(dictionary_empty))
# creating a non empty dictionary
dictio={"key 1":13,
      "key 2": 23,
      "key 3": 33}
print(dictio)
print(dictio["key 1"])
# inserting a value in dictionary
dictio["Key 4"]=44
print(dictio)
#updating a value in dictionary
dictio["Key 4"]=4400
print(dictio)


<class 'dict'>
{'key 1': 13, 'key 2': 23, 'key 3': 33}
13
{'key 1': 13, 'key 2': 23, 'key 3': 33, 'Key 4': 44}
{'key 1': 13, 'key 2': 23, 'key 3': 33, 'Key 4': 4400}


In [ ]:
# iterate through keys, values and items (items mean both keys and values)
for v1,v2 in dictio.items():
  print(v1,v2)
for (v1) in dictio.keys():
  print(v1)
for (v1) in dictio.values():
  print(v1)

key 3 33
Key 4 4400
key 3
Key 4
33
4400


In [ ]:
# searching for an element in dictionary. This is my ways without following any grammar. But I am happy!
print(dictio)
listi_keys=[]
listi_values=[]
for i in dictio.keys():
  listi_keys.append(i)
for j in dictio.values():
  listi_values.append(j)
print(listi_keys)
print(listi_values)
for i in range(len(listi_values)):
  if listi_values[i]==4400:
    print(listi_keys[i])

{'key 3': 33, 'Key 4': 4400}
['key 3', 'Key 4']
[33, 4400]
Key 4


In [ ]:
# easy way
def dictionary_search(dictionary,value):
  for (i,j) in dictionary.items():
    if dictionary[i]==value:
      return i,j
  return "the value doesn't exist"
dictionary_search(dictio,23)

('key 2', 23)

In [ ]:
# delete/remove an item from the dictionary
my_dict1={'uno':1,
          'des':2,
          'tres':3,
          'kappa':4}
del my_dict1['des']
print(my_dict1)
my_dict1.popitem()
print(my_dict1)
my_dict1.clear()
print(my_dict1)

{'uno': 1, 'tres': 3, 'kappa': 4}
{'uno': 1, 'tres': 3}
{}


In [ ]:
# dictionary copy
dict_method={'first':10,
             'second':20,
             'third':30,
             'fourth':40,
             'fifth':50

}
another_dict=dict_method.copy()

In [ ]:
# from keys # didn't understand, watch video
new_dict={}.fromkeys(['first','second','third'],0)
new_dict1={}.fromkeys(['first','second','third'])
print(new_dict)
print(new_dict1)

{'first': 0, 'second': 0, 'third': 0}
{'first': None, 'second': None, 'third': None}


In [ ]:
print(another_dict)

{'first': 10, 'second': 20, 'third': 30, 'fourth': 40, 'fifth': 50}


In [ ]:
print(another_dict.get('first')) # it returns the value of the key specified

10


In [ ]:
# get_method
print(another_dict.items())
print(another_dict.keys())
print(another_dict.values())
print(another_dict.popitem())


NameError: ignored

In [ ]:
print(another_dict.setdefault('first',100))
print(another_dict.pop('first',10))
print(another_dict.update(new_dict1)) # didn't understand

NameError: ignored

In [ ]:
dictio

{}

In [ ]:
print(another_dict)

{'second': 20, 'third': 30, 'fourth': 40, 'fifth': 50, 'key 3': 33, 'Key 4': 4400}


100000
{'first': 10, 'second': 20, 'third': 30, 'fourth': 40, 'fifth': 50}
dict_keys(['first', 'second', 'third', 'fourth', 'fifth'])
dict_values([10, 20, 30, 40, 50])


In [ ]:
# dictionary built in operations/functions watch video
new_dict2={'a':1,'b':2,'c':3, 'd':4, 'e':5}
print(new_dict2)
print('a' in new_dict2)
print('a' in new_dict2.keys())
print(1 in new_dict2.values())
# len function
print(len(new_dict2))





{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
True
True
True
5


In [ ]:
# more on functions in dictionary # didn't understand watch video
mydict = {"Apple" :0 , "na" : "Orange"}
x = all(mydict)
print(x)
# any function
# sorted function



True


In [ ]:
# dictionary comprehension
# dictionary comprehension is the syntax to create a dictionary in short form
#new_dict={new_key:new_value for items in list}
# create a dictionary based on the values of from the existing dictionary
#new_dict={new_key:new_value for (key, value) in dict.items()}
# adding a condition
# #new_dict={new_key:new_value for (key, value) in dict.items() if condition}

In [ ]:
# practicing dictionary comprehention
import random
random.seed(10)
city_names=['dhaka','NYC','Florida','New delhi']
temp=[10,34,45,24]
city_dict={city:random.randint(20,30) for city in city_names}
print(city_dict)

{'dhaka': 29, 'NYC': 20, 'Florida': 26, 'New delhi': 27}


In [ ]:
random.randint(20,30)

In [ ]:
# new_dict={new_key:new_value for (key, value) in dict.items() if condition}
new_dict={city:temp for (city, temp) in city_dict.items() }
print(new_dict)
new_dict_if={city:temp for (city, temp) in city_dict.items() if temp>26 }
print(new_dict_if)

{'dhaka': 29, 'NYC': 20, 'Florida': 26, 'New delhi': 27}
{'dhaka': 29, 'New delhi': 27}


**Section:10 Tuples**

In [ ]:
#create a tuple
new_tuple=('a','b','c','d','e')
new_tuple1=('a',)
new_tuple2=tuple()
print(new_tuple)
print(new_tuple1)
print(new_tuple2)

('a', 'b', 'c', 'd', 'e')
('a',)
()


In [ ]:
# access elements in tuple and traverse
new_tuple[0:3]
for i in new_tuple:
  print(i, end=" ")
for i in range(len(new_tuple)):
  print(new_tuple[i])

a b c d e a
b
c
d
e


In [ ]:
# searching for an element in tuple
new_tuple3=(1,7,8,9,77,88,99)
print(new_tuple3[3])
print(new_tuple3.index(77))
# searching using function
def search_tuple(ttuple,value):
  for i in range(len(ttuple)):
    if ttuple[i]==value:
      return i,value
  return "Can't do"
search_tuple(new_tuple3,88)


9
4


(5, 88)

In [ ]:
# Tuple operations/functions
# concetanate tuple
tuple1=(1,2,3,4,5)
tuple2=(6,7)
tuple1+tuple2
tuple1*2
# in operator
1 in tuple1
print(tuple1.count(2))
print(tuple1.index(3))
# len, min, max,
# converting tuple to list
print(tuple([1,2,3,4,5]))


In [ ]:
# we can't change a single element in tuple but we can reassign the whole tuple
t1=(1,2,3)
t1=(5,6,7)
print(t1)# we can't delete elements but full tuple

In [ ]:
# Define a function to count the frequency of words in a given list of words.
# Example:
#words = ['apple', 'orange', 'banana', 'apple', 'orange', 'apple']
#count_word_frequency(words)
#Output: {'apple': 3, 'orange': 2, 'banana': 1}
words = ['apple', 'orange', 'banana', 'apple', 'orange', 'apple','apple']
apple_count=0
orange_count=0
banana_count=0
for i in words:
  if i=='apple':
    apple_count+=1
  if i=='banana':
    banana_count+=1
  if i=='orange':
    orange_count+=1
print(apple_count, banana_count,orange_count)

4 1 2


In [ ]:
# Define a function with takes two dictionaries as parameters and merge them and sum the values of common keys.
dict1 = {'a': 1, 'b': 2, 'c': 3}
dict2 = {'b': 3, 'c': 4, 'd': 5}
dict3=dict2.update(dict1)



{'a': 1, 'b': 5, 'c': 7, 'd': 5}

{'a': 1, 'b': 5, 'c': 7, 'd': 5}